# Form implementation generated from reading ui file 'dialog2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(406, 180)
        Form.setStyleSheet("background: #00BFFF;")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(60, 90, 131, 61))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"color: #00BFFF;\n"
"border: 2px solid rgb(59, 131, 189);\n"
"border-radius: 30;\n"
"font: 18pt \".AppleSystemUIFont\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 90, 131, 61))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"color: #00BFFF;\n"
"border: 2px solid rgb(59, 131, 189);\n"
"border-radius: 30;\n"
"font: 18pt \".AppleSystemUIFont\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 255, 255);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 381, 31))
        self.textBrowser.setStyleSheet("border: 0px;\n"
"font: 18pt \".AppleSystemUIFont\";")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Ок"))
        self.pushButton_2.setText(_translate("Form", "Отмена"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Записать диапазон?</span></p></body></html>"))

