# Form implementation generated from reading ui file 'MainTable.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #00BFFF;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 60, 711, 431))
        self.tableWidget.setStyleSheet("background: white;\n"
"    color: #00BFFF;\n")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.CustomDashLine)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.horizontalHeader().setDefaultSectionSize(230)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(19)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 711, 41))
        self.label.setStyleSheet("color: white;\n"
"font: 22pt;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 511, 201, 61))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #00BFFF;\n"
"    background-color: white;\n"
"    border: 2px solid rgb(59, 131, 189);\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(200, 255, 255);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 510, 201, 61))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: #00BFFF;\n"
"    background-color: white;\n"
"    border: 2px solid rgb(59, 131, 189);\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(200, 255, 255);\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 510, 201, 61))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color: #00BFFF;\n"
"    background-color: white;\n"
"    border: 2px solid rgb(59, 131, 189);\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(200, 255, 255);\n"
"}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setSortingEnabled(True)
        self.label.setText(_translate("MainWindow", "Таблица данных строчных применимостей"))
        self.pushButton.setText(_translate("MainWindow", "ВВОД ДАННЫХ"))
        self.pushButton_2.setText(_translate("MainWindow", "УДАЛИТь СТРОКУ"))
        self.pushButton_3.setText(_translate("MainWindow", "ЗАКРЫТЬ"))
